spring:
  datasource:
    password: petz
    url: jdbc:postgresql://localhost:5432/petz?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: petz
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration
